import { Question, Domain } from './types';

export const questions: Question[] = [
  // --- 1.0 Network Programmability Foundation ---
  { id: '1-1', domain: Domain.NPF, q: 'Git: Command to unstage a file but keep changes in working directory?', a: 'git reset HEAD <file>', d: ['git checkout <file>', 'git rm --cached <file>', 'git revert <file>'] },
  { id: '1-2', domain: Domain.NPF, q: 'Git: Command to undo the last commit and keep changes staged?', a: 'git reset --soft HEAD~1', d: ['git reset --mixed HEAD~1', 'git reset --hard HEAD~1', 'git revert HEAD'] },
  { id: '1-3', domain: Domain.NPF, q: 'Git: Command to completely discard all local changes in working directory?', a: 'git reset --hard', d: ['git reset --soft', 'git clean -f', 'git checkout .'] },
  { id: '1-4', domain: Domain.NPF, q: 'Git: Applies changes from a specific commit to current branch?', a: 'git cherry-pick <commit-hash>', d: ['git rebase <commit-hash>', 'git merge <commit-hash>', 'git apply <commit-hash>'] },
  { id: '1-5', domain: Domain.NPF, q: 'Git: Command to create a new branch and switch to it immediately?', a: 'git checkout -b <branch-name>', d: ['git branch <branch-name>', 'git switch <branch-name>', 'git branch -m <branch-name>'] },
  { id: '1-6', domain: Domain.NPF, q: 'REST vs RPC: Which typically uses a single URI endpoint for multiple actions?', a: 'RPC', d: ['REST', 'GraphQL', 'SOAP'] },
  { id: '1-7', domain: Domain.NPF, q: 'REST vs RPC: Which is resource-centric?', a: 'REST', d: ['RPC', 'gRPC', 'XML-RPC'] },
  { id: '1-8', domain: Domain.NPF, q: 'Async API: What HTTP status code typically indicates "Accepted/Processing"?', a: '202 Accepted', d: ['200 OK', '201 Created', '204 No Content'] },
  { id: '1-9', domain: Domain.NPF, q: 'Python: Mutable data type defined with square brackets []?', a: 'List', d: ['Tuple', 'Set', 'Dictionary'] },
  { id: '1-10', domain: Domain.NPF, q: 'Python: Immutable data type defined with parentheses ()?', a: 'Tuple', d: ['List', 'Set', 'Dictionary'] },
  { id: '1-11', domain: Domain.NPF, q: 'Python: Unordered collection of unique elements?', a: 'Set', d: ['List', 'Tuple', 'Dictionary'] },
  { id: '1-12', domain: Domain.NPF, q: 'Python: Syntax to define a class method?', a: 'def method_name(self):', d: ['function method_name(self):', 'method method_name():', 'def method_name():'] },
  { id: '1-13', domain: Domain.NPF, q: 'Python: Library used for standard HTTP requests?', a: 'requests', d: ['urllib', 'http', 'httplib'] },
  { id: '1-14', domain: Domain.NPF, q: 'Python: Command to create a virtual environment?', a: 'python3 -m venv <dir>', d: ['python3 --venv <dir>', 'pip install venv <dir>', 'virtualenv --create <dir>'] },
  { id: '1-15', domain: Domain.NPF, q: 'Terraform: What file tracks the current state of infrastructure?', a: 'terraform.tfstate', d: ['terraform.tf', 'main.tf', 'state.tf'] },
  { id: '1-16', domain: Domain.NPF, q: 'Ansible: What format are Playbooks written in?', a: 'YAML', d: ['JSON', 'XML', 'INI'] },
  { id: '1-17', domain: Domain.NPF, q: 'Terraform: Command to preview changes before applying?', a: 'terraform plan', d: ['terraform preview', 'terraform check', 'terraform validate'] },
  { id: '1-18', domain: Domain.NPF, q: 'Ansible: Type of loop used with `loop` keyword?', a: 'Standard iteration (formerly with_items)', d: ['with_list', 'foreach', 'iterate'] },
  { id: '1-19', domain: Domain.NPF, q: 'Sync API: The client must do what?', a: 'Wait for the response before proceeding', d: ['Poll for status updates', 'Register a callback', 'Subscribe to events'] },
  { id: '1-20', domain: Domain.NPF, q: 'Git: Command to temporarily save changes without committing?', a: 'git stash', d: ['git save', 'git store', 'git cache'] },

  // --- 2.0 ACI ---
  { id: '2-1', domain: Domain.ACI, q: 'ACI API: URI to query a specific object by DN?', a: '/api/mo/<dn>.json', d: ['/api/class/<dn>.json', '/api/node/<dn>.json', '/api/dn/<dn>.json'] },
  { id: '2-2', domain: Domain.ACI, q: 'ACI API: URI to query all objects of a specific class?', a: '/api/class/<className>.json', d: ['/api/mo/<className>.json', '/api/objects/<className>.json', '/api/query/<className>.json'] },
  { id: '2-3', domain: Domain.ACI, q: 'ACI API: Query param to include child objects in response?', a: 'query-target=subtree', d: ['query-target=children', 'rsp-subtree=full', 'include=children'] },
  { id: '2-4', domain: Domain.ACI, q: 'ACI API: Query param to filter results based on property values?', a: 'query-target-filter', d: ['property-filter', 'rsp-filter', 'object-filter'] },
  { id: '2-5', domain: Domain.ACI, q: 'ACI Filter: Function to match exact string?', a: 'eq(item, "value")', d: ['match(item, "value")', 'exact(item, "value")', 'equals(item, "value")'] },
  { id: '2-6', domain: Domain.ACI, q: 'ACI Filter: Function to match partial string?', a: 'wcard(item, "val*")', d: ['like(item, "val*")', 'contains(item, "val")', 'match(item, "val*")'] },
  { id: '2-7', domain: Domain.ACI, q: 'Cobra SDK: Class used to authenticate?', a: 'LoginSession', d: ['AuthSession', 'ApicSession', 'UserSession'] },
  { id: '2-8', domain: Domain.ACI, q: 'Cobra SDK: Object that holds the MIT structure locally?', a: 'MoDirectory', d: ['MitTree', 'ObjectStore', 'LocalMit'] },
  { id: '2-9', domain: Domain.ACI, q: 'Cobra SDK: Method to commit changes to APIC?', a: 'commit(configRequest)', d: ['push(configRequest)', 'save(configRequest)', 'apply(configRequest)'] },
  { id: '2-10', domain: Domain.ACI, q: 'Cobra SDK: Method to find an object by its DN?', a: 'lookupByDn', d: ['queryByDn', 'findByDn', 'getByDn'] },
  { id: '2-11', domain: Domain.ACI, q: 'Ansible ACI: Module param for Application Profile?', a: 'ap', d: ['app_profile', 'application', 'profile'] },
  { id: '2-12', domain: Domain.ACI, q: 'Ansible ACI: Module param for Bridge Domain?', a: 'bd', d: ['bridge_domain', 'domain', 'bridge'] },
  { id: '2-13', domain: Domain.ACI, q: 'Ansible ACI: Relation parameter for Context (VRF)?', a: 'relation_fv_rs_ctx', d: ['vrf', 'context', 'relation_vrf'] },
  { id: '2-14', domain: Domain.ACI, q: 'Terraform ACI: Format for relation_fv_rs_cons?', a: 'List of strings (DNs)', d: ['Single string (DN)', 'Map of objects', 'Set of names'] },
  { id: '2-15', domain: Domain.ACI, q: 'Terraform ACI: Subnet notation requirement?', a: 'CIDR format (e.g., 10.0.0.1/24)', d: ['Dotted decimal only', 'Subnet mask format', 'Hex notation'] },
  { id: '2-16', domain: Domain.ACI, q: 'Tool: Built-in APIC tool to view API messages for GUI actions?', a: 'API Inspector', d: ['Visore', 'API Explorer', 'Object Browser'] },
  { id: '2-17', domain: Domain.ACI, q: 'Tool: Object Browser for ACI?', a: 'Visore', d: ['API Inspector', 'MO Explorer', 'Object Viewer'] },
  { id: '2-18', domain: Domain.ACI, q: 'ACI Class: Root class for a Tenant?', a: 'fvTenant', d: ['tnTenant', 'aciTenant', 'polTenant'] },
  { id: '2-19', domain: Domain.ACI, q: 'ACI Class: Class for a VRF?', a: 'fvCtx', d: ['fvVrf', 'l3Ctx', 'vrfInst'] },
  { id: '2-20', domain: Domain.ACI, q: 'ACI Class: Class for an EPG?', a: 'fvAEPg', d: ['fvEpg', 'fvEndpointGroup', 'epgInst'] },
  { id: '2-21', domain: Domain.ACI, q: 'ACI CNI: Main benefit for Kubernetes?', a: 'Maps K8s namespaces/pods to ACI EPGs', d: ['Provides container runtime', 'Manages K8s nodes', 'Replaces kube-proxy'] },
  { id: '2-22', domain: Domain.ACI, q: 'ACI API: Default format if not specified?', a: 'XML (usually, though JSON is preferred)', d: ['JSON', 'YAML', 'Plain text'] },
  { id: '2-23', domain: Domain.ACI, q: 'ACI API: Property to specify target subtree class?', a: 'target-subtree-class', d: ['subtree-class-filter', 'child-class', 'rsp-subtree-class'] },
  { id: '2-24', domain: Domain.ACI, q: 'Cobra: How to delete an MO?', a: 'mo.delete()', d: ['mo.remove()', 'directory.delete(mo)', 'mo.destroy()'] },
  { id: '2-25', domain: Domain.ACI, q: 'Ansible ACI: Typical state for deletion?', a: 'absent', d: ['deleted', 'removed', 'destroy'] },
  { id: '2-26', domain: Domain.ACI, q: 'Ansible ACI: Relation parameter for BD to VRF?', a: 'relation_fv_rs_ctx', d: ['vrf_name', 'bd_to_vrf', 'context_relation'] },
  { id: '2-27', domain: Domain.ACI, q: 'ACI Class: Relationship from EPG to BD?', a: 'fvRsBd', d: ['fvRsEpgBd', 'fvRelBd', 'epgRsBd'] },
  { id: '2-28', domain: Domain.ACI, q: 'ACI Class: Relationship from BD to VRF?', a: 'fvRsCtx', d: ['fvRsVrf', 'bdRsCtx', 'fvRelCtx'] },
  { id: '2-29', domain: Domain.ACI, q: 'ACI API: Filter logic for "NOT"?', a: 'not()', d: ['ne()', 'exclude()', '!()'] },
  { id: '2-30', domain: Domain.ACI, q: 'ACI API: Filter logic for "AND"?', a: 'and()', d: ['&&()', 'all()', 'both()'] },
  { id: '2-31', domain: Domain.ACI, q: 'Terraform ACI: Argument to set EPG description?', a: 'description', d: ['desc', 'descr', 'comment'] },
  { id: '2-32', domain: Domain.ACI, q: 'Cobra: Argument to specify parent MO during creation?', a: 'parentMoOrDn', d: ['parent', 'parentDn', 'parentObject'] },
  { id: '2-33', domain: Domain.ACI, q: 'Visore: Default URL path?', a: '/visore.html', d: ['/api/visore', '/apic/visore', '/inspector.html'] },
  { id: '2-34', domain: Domain.ACI, q: 'ACI Class: Physical Domain profile?', a: 'physDomP', d: ['phyDomain', 'l1DomP', 'infraDomP'] },
  { id: '2-35', domain: Domain.ACI, q: 'ACI Class: VLAN Pool?', a: 'fvnsVlanInstP', d: ['vlanPool', 'fvVlanPool', 'infraVlanP'] },
  { id: '2-36', domain: Domain.ACI, q: 'Ansible: Module for generic ACI REST calls?', a: 'aci_rest', d: ['aci_api', 'aci_request', 'aci_raw'] },
  { id: '2-37', domain: Domain.ACI, q: 'ACI API: Status code for successful login?', a: '200 OK', d: ['201 Created', '204 No Content', '202 Accepted'] },
  { id: '2-38', domain: Domain.ACI, q: 'ACI: Logical container for policies?', a: 'Tenant', d: ['Fabric', 'Pod', 'Domain'] },
  { id: '2-39', domain: Domain.ACI, q: 'Cobra: Python package name?', a: 'acicobra', d: ['cobra', 'cisco-cobra', 'aci-sdk'] },
  { id: '2-40', domain: Domain.ACI, q: 'Terraform: Provider name for ACI?', a: 'CiscoDevNet/aci', d: ['cisco/aci', 'hashicorp/aci', 'aci/terraform'] },

  // --- 3.0 NX-OS ---
  { id: '3-1', domain: Domain.NXOS, q: 'POAP: Script must be written in?', a: 'Python (or TCL)', d: ['Bash', 'Perl', 'Ruby'] },
  { id: '3-2', domain: Domain.NXOS, q: 'POAP: Top of script requirement to import CLI functions?', a: 'from cli import *', d: ['import cli', 'from nxos import cli', 'import nxapi'] },
  { id: '3-3', domain: Domain.NXOS, q: 'NX-OS Python: Function to run CLI and return raw string?', a: 'cli()', d: ['clid()', 'clip()', 'clis()'] },
  { id: '3-4', domain: Domain.NXOS, q: 'NX-OS Python: Function to run CLI and return JSON/Dict?', a: 'clid()', d: ['cli()', 'clip()', 'clij()'] },
  { id: '3-5', domain: Domain.NXOS, q: 'NX-OS Python: Function to run CLI and print directly to stdout?', a: 'clip()', d: ['cli()', 'clid()', 'clio()'] },
  { id: '3-6', domain: Domain.NXOS, q: 'Guest Shell: Command to execute command on host switch?', a: 'dohost', d: ['runhost', 'nxcli', 'switchcmd'] },
  { id: '3-7', domain: Domain.NXOS, q: 'Guest Shell: Native shell type?', a: 'Bash (CentOS based)', d: ['Zsh (Ubuntu based)', 'Sh (Alpine based)', 'Fish (Debian based)'] },
  { id: '3-8', domain: Domain.NXOS, q: 'EEM: Action to execute a config command?', a: 'action <n> cli command "<cmd>"', d: ['action <n> exec "<cmd>"', 'action <n> run "<cmd>"', 'action <n> config "<cmd>"'] },
  { id: '3-9', domain: Domain.NXOS, q: 'NX-API CLI: Message format type for show commands?', a: 'cli_show', d: ['cli_exec', 'cli_display', 'show_cmd'] },
  { id: '3-10', domain: Domain.NXOS, q: 'NX-API CLI: Message format type for config commands?', a: 'cli_conf', d: ['cli_config', 'conf_cmd', 'cli_set'] },
  { id: '3-11', domain: Domain.NXOS, q: 'NX-API REST: URL path for DME access?', a: '/api/mo/', d: ['/api/dme/', '/ins/api/', '/rest/mo/'] },
  { id: '3-12', domain: Domain.NXOS, q: 'NETCONF: Port number?', a: '830', d: ['22', '443', '8443'] },
  { id: '3-13', domain: Domain.NXOS, q: 'NETCONF: Operation to change configuration?', a: 'edit-config', d: ['set-config', 'modify-config', 'update-config'] },
  { id: '3-14', domain: Domain.NXOS, q: 'NETCONF: Operation to retrieve running config?', a: 'get-config', d: ['read-config', 'fetch-config', 'show-config'] },
  { id: '3-15', domain: Domain.NXOS, q: 'NETCONF: Default edit operation (merge/replace/none)?', a: 'merge', d: ['replace', 'none', 'create'] },
  { id: '3-16', domain: Domain.NXOS, q: 'gNMI: Supported encoding formats?', a: 'JSON, Bytes (Protobuf)', d: ['XML, YAML', 'JSON, XML', 'YAML, Protobuf'] },
  { id: '3-17', domain: Domain.NXOS, q: 'gNMI: RPC to stream data?', a: 'Subscribe', d: ['Stream', 'Watch', 'Listen'] },
  { id: '3-18', domain: Domain.NXOS, q: 'Telemetry: "Dial-out" means?', a: 'Device initiates connection to collector', d: ['Collector initiates connection to device', 'Device polls collector', 'Push via SNMP trap'] },
  { id: '3-19', domain: Domain.NXOS, q: 'Telemetry: "Dial-in" means?', a: 'Collector initiates connection to device', d: ['Device initiates connection to collector', 'Collector polls device', 'Device sends SNMP trap'] },
  { id: '3-20', domain: Domain.NXOS, q: 'NX-OS Telemetry: Interval unit?', a: 'Milliseconds', d: ['Seconds', 'Minutes', 'Microseconds'] },
  { id: '3-21', domain: Domain.NXOS, q: 'YANG: Google-defined vendor-neutral models?', a: 'OpenConfig', d: ['IETF', 'Native', 'Cisco-common'] },
  { id: '3-22', domain: Domain.NXOS, q: 'YANG: Cisco specific models?', a: 'Native', d: ['OpenConfig', 'IETF', 'Vendor'] },
  { id: '3-23', domain: Domain.NXOS, q: 'NX-API: Default HTTP port?', a: '80', d: ['8080', '443', '8443'] },
  { id: '3-24', domain: Domain.NXOS, q: 'NX-API: Default HTTPS port?', a: '443', d: ['8443', '8080', '9443'] },
  { id: '3-25', domain: Domain.NXOS, q: 'NX-API: Sandbox URL?', a: '/ins', d: ['/api', '/sandbox', '/nxapi'] },
  { id: '3-26', domain: Domain.NXOS, q: 'NETCONF: Filter type to select specific nodes?', a: 'subtree', d: ['xpath', 'path', 'node'] },
  { id: '3-27', domain: Domain.NXOS, q: 'EEM: Event detector for syslog?', a: 'event syslog', d: ['event log', 'event message', 'event alert'] },
  { id: '3-28', domain: Domain.NXOS, q: 'EEM: Event detector for CLI command?', a: 'event cli match', d: ['event command', 'event exec', 'event input'] },
  { id: '3-29', domain: Domain.NXOS, q: 'Guest Shell: Packet manager?', a: 'yum', d: ['apt', 'pip', 'dnf'] },
  { id: '3-30', domain: Domain.NXOS, q: 'NX-OS Python: How to separate multiple commands in one string?', a: ' ; (semicolon)', d: [' && (double ampersand)', ' | (pipe)', ' \n (newline)'] },
  { id: '3-31', domain: Domain.NXOS, q: 'Model Driven Telemetry: Encoding using Key/Value pairs?', a: 'GPB-KV (Google Protobuf Key Value)', d: ['GPB (Google Protobuf)', 'JSON', 'CBOR'] },
  { id: '3-32', domain: Domain.NXOS, q: 'Model Driven Telemetry: Compact encoding?', a: 'GPB (Google Protobuf)', d: ['GPB-KV (Google Protobuf Key Value)', 'JSON-compact', 'MessagePack'] },
  { id: '3-33', domain: Domain.NXOS, q: 'NETCONF: Python library often used?', a: 'ncclient', d: ['netconf', 'pynetconf', 'cisco-netconf'] },
  { id: '3-34', domain: Domain.NXOS, q: 'NX-API REST: Payload format?', a: 'JSON or XML', d: ['JSON only', 'XML only', 'YAML or JSON'] },
  { id: '3-35', domain: Domain.NXOS, q: 'NX-OS: Feature to enable API?', a: 'feature nxapi', d: ['feature restapi', 'feature api', 'feature http-api'] },
  { id: '3-36', domain: Domain.NXOS, q: 'NX-OS: Feature to enable NETCONF?', a: 'feature netconf', d: ['feature ssh', 'feature xml-agent', 'feature yang'] },
  { id: '3-37', domain: Domain.NXOS, q: 'NX-OS: Feature to enable Bash?', a: 'feature bash-shell', d: ['feature bash', 'feature shell', 'feature linux-shell'] },
  { id: '3-38', domain: Domain.NXOS, q: 'gNMI: Transport protocol?', a: 'HTTP/2 (gRPC)', d: ['HTTP/1.1', 'TCP', 'WebSocket'] },
  { id: '3-39', domain: Domain.NXOS, q: 'POAP: DHCP option for script URI?', a: 'Option 66/67', d: ['Option 43', 'Option 150', 'Option 82'] },
  { id: '3-40', domain: Domain.NXOS, q: 'YANG: Leaf node constraint?', a: 'must', d: ['when', 'require', 'assert'] },

  // --- 4.0 UCS/Intersight ---
  { id: '4-1', domain: Domain.UCS, q: 'UCS Python SDK: Function to add an MO?', a: 'add_mo', d: ['create_mo', 'insert_mo', 'new_mo'] },
  { id: '4-2', domain: Domain.UCS, q: 'UCS Python SDK: Argument to update if exists?', a: 'modify_present=True', d: ['update_existing=True', 'overwrite=True', 'upsert=True'] },
  { id: '4-3', domain: Domain.UCS, q: 'UCS Python SDK: Is there a set_mo function?', a: 'No (use add_mo with modify_present)', d: ['Yes (set_mo)', 'Yes (update_mo)', 'Yes (modify_mo)'] },
  { id: '4-4', domain: Domain.UCS, q: 'LsServer: Type for a Service Profile Template?', a: 'initial-template / updating-template', d: ['template', 'instance', 'derived'] },
  { id: '4-5', domain: Domain.UCS, q: 'LsServer: Type for a Service Profile Instance?', a: 'instance', d: ['template', 'derived', 'deployed'] },
  { id: '4-6', domain: Domain.UCS, q: 'PowerTool: Pattern to modify objects?', a: 'Get-UcsX | Set-UcsX', d: ['Find-UcsX | Update-UcsX', 'Select-UcsX | Modify-UcsX', 'Query-UcsX | Change-UcsX'] },
  { id: '4-7', domain: Domain.UCS, q: 'PowerTool: Flag to confirm XML output?', a: '-Xml', d: ['-Format Xml', '-OutputXml', '-AsXml'] },
  { id: '4-8', domain: Domain.UCS, q: 'Intersight Auth: Hashing algorithm for body?', a: 'SHA256', d: ['SHA512', 'MD5', 'SHA1'] },
  { id: '4-9', domain: Domain.UCS, q: 'Intersight Auth: Signature algorithm?', a: 'RSA', d: ['HMAC', 'ECDSA', 'DSA'] },
  { id: '4-10', domain: Domain.UCS, q: 'Intersight API: Mandatory relationship for most resources?', a: 'Organization', d: ['Account', 'Tenant', 'Project'] },
  { id: '4-11', domain: Domain.UCS, q: 'Intersight API: Organization reference requires?', a: 'moid and object_type', d: ['name only', 'dn only', 'uuid and name'] },
  { id: '4-12', domain: Domain.UCS, q: 'Terraform Intersight: Authentication requires?', a: 'apikey and secretkey (file)', d: ['username and password', 'token only', 'certificate and key'] },
  { id: '4-13', domain: Domain.UCS, q: 'UCS Python SDK: Module to import?', a: 'ucsmsdk', d: ['ucssdk', 'cisco_ucs', 'pyucs'] },
  { id: '4-14', domain: Domain.UCS, q: 'UCS Manager: XML API endpoint?', a: '/nuova', d: ['/api', '/xmlapi', '/ucsm'] },
  { id: '4-15', domain: Domain.UCS, q: 'Intersight: Query parameter to filter?', a: '$filter', d: ['$query', '$where', '$match'] },
  { id: '4-16', domain: Domain.UCS, q: 'Intersight: Query parameter to select specific fields?', a: '$select', d: ['$fields', '$include', '$columns'] },
  { id: '4-17', domain: Domain.UCS, q: 'UCS Class: Compute Blade?', a: 'computeBlade', d: ['bladeSrvr', 'ucsBlade', 'serverBlade'] },
  { id: '4-18', domain: Domain.UCS, q: 'UCS Class: Rack Unit?', a: 'computeRackUnit', d: ['rackServer', 'ucsRack', 'serverRack'] },
  { id: '4-19', domain: Domain.UCS, q: 'Intersight: Header containing the signature?', a: 'Authorization', d: ['X-Signature', 'Signature', 'X-Auth-Signature'] },
  { id: '4-20', domain: Domain.UCS, q: 'Intersight: Header containing the date?', a: 'Date (or X-Date)', d: ['X-Timestamp', 'Request-Date', 'X-Request-Time'] },
  { id: '4-21', domain: Domain.UCS, q: 'UCS Python SDK: Login handle class?', a: 'UcsHandle', d: ['UcsSession', 'UcsConnection', 'UcsLogin'] },
  { id: '4-22', domain: Domain.UCS, q: 'PowerTool: Cmdlet to connect?', a: 'Connect-Ucs', d: ['New-UcsSession', 'Open-Ucs', 'Start-UcsConnection'] },
  { id: '4-23', domain: Domain.UCS, q: 'PowerTool: Cmdlet to disconnect?', a: 'Disconnect-Ucs', d: ['Close-Ucs', 'Remove-UcsSession', 'Stop-UcsConnection'] },
  { id: '4-24', domain: Domain.UCS, q: 'Intersight: Object Type for physical server?', a: 'compute.PhysicalSummary', d: ['server.Physical', 'compute.Server', 'hardware.Server'] },
  { id: '4-25', domain: Domain.UCS, q: 'Intersight: Object Type for organization?', a: 'organization.Organization', d: ['iam.Organization', 'resource.Organization', 'tenant.Organization'] },
  { id: '4-26', domain: Domain.UCS, q: 'Terraform Intersight: Provider name?', a: 'CiscoDevNet/intersight', d: ['cisco/intersight', 'hashicorp/intersight', 'intersight/terraform'] },
  { id: '4-27', domain: Domain.UCS, q: 'UCS Python: Query class objects?', a: 'handle.query_classid("classId")', d: ['handle.get_class("classId")', 'handle.find_classid("classId")', 'handle.search_class("classId")'] },
  { id: '4-28', domain: Domain.UCS, q: 'UCS Python: Commit transaction?', a: 'handle.commit()', d: ['handle.save()', 'handle.apply()', 'handle.push()'] },
  { id: '4-29', domain: Domain.UCS, q: 'UCS Python: Logout?', a: 'handle.logout()', d: ['handle.disconnect()', 'handle.close()', 'handle.end()'] },
  { id: '4-30', domain: Domain.UCS, q: 'Intersight API: Base URL?', a: 'https://intersight.com/api/v1', d: ['https://api.intersight.com/v1', 'https://intersight.cisco.com/api', 'https://cloud.intersight.com/api/v1'] },
];
