import { Question, Domain } from './types';

export const questions: Question[] = [
  // --- 1.0 Network Programmability Foundation ---
  { id: '1-1', domain: Domain.NPF, q: 'Git: Command to unstage a file but keep changes in working directory?', a: 'git reset HEAD <file>', d: ['git checkout <file>', 'git rm --cached <file>', 'git revert <file>'] },
  { id: '1-2', domain: Domain.NPF, q: 'Git: Command to undo the last commit and keep changes staged?', a: 'git reset --soft HEAD~1', d: ['git reset --mixed HEAD~1', 'git reset --hard HEAD~1', 'git revert HEAD'] },
  { id: '1-3', domain: Domain.NPF, q: 'Git: Command to completely discard all local changes in working directory?', a: 'git reset --hard', d: ['git reset --soft', 'git clean -f', 'git checkout .'] },
  { id: '1-4', domain: Domain.NPF, q: 'Git: Applies changes from a specific commit to current branch?', a: 'git cherry-pick <commit-hash>', d: ['git rebase <commit-hash>', 'git merge <commit-hash>', 'git apply <commit-hash>'] },
  { id: '1-5', domain: Domain.NPF, q: 'Git: Command to create a new branch and switch to it immediately?', a: 'git checkout -b <branch-name>', d: ['git branch <branch-name>', 'git switch <branch-name>', 'git branch -m <branch-name>'] },
  { id: '1-6', domain: Domain.NPF, q: 'REST vs RPC: Which typically uses a single URI endpoint for multiple actions?', a: 'RPC', d: ['REST', 'GraphQL', 'SOAP'] },
  { id: '1-7', domain: Domain.NPF, q: 'REST vs RPC: Which is resource-centric?', a: 'REST', d: ['RPC', 'gRPC', 'XML-RPC'] },
  { id: '1-8', domain: Domain.NPF, q: 'Async API: What HTTP status code typically indicates "Accepted/Processing"?', a: '202 Accepted', d: ['200 OK', '201 Created', '204 No Content'] },
  { id: '1-9', domain: Domain.NPF, q: 'Python: Mutable data type defined with square brackets []?', a: 'List', d: ['Tuple', 'Set', 'Dictionary'] },
  { id: '1-10', domain: Domain.NPF, q: 'Python: Immutable data type defined with parentheses ()?', a: 'Tuple', d: ['List', 'Set', 'Dictionary'] },
  { id: '1-11', domain: Domain.NPF, q: 'Python: Unordered collection of unique elements?', a: 'Set', d: ['List', 'Tuple', 'Dictionary'] },
  { id: '1-12', domain: Domain.NPF, q: 'Python: Syntax to define a class method?', a: 'def method_name(self):', d: ['function method_name(self):', 'method method_name():', 'def method_name():'] },
  { id: '1-13', domain: Domain.NPF, q: 'Python: Library used for standard HTTP requests?', a: 'requests', d: ['urllib', 'http', 'httplib'] },
  { id: '1-14', domain: Domain.NPF, q: 'Python: Command to create a virtual environment?', a: 'python3 -m venv <dir>', d: ['python3 --venv <dir>', 'pip install venv <dir>', 'virtualenv --create <dir>'] },
  { id: '1-15', domain: Domain.NPF, q: 'Terraform: What file tracks the current state of infrastructure?', a: 'terraform.tfstate', d: ['terraform.tf', 'main.tf', 'state.tf'] },
  { id: '1-16', domain: Domain.NPF, q: 'Ansible: What format are Playbooks written in?', a: 'YAML', d: ['JSON', 'XML', 'INI'] },
  { id: '1-17', domain: Domain.NPF, q: 'Terraform: Command to preview changes before applying?', a: 'terraform plan', d: ['terraform preview', 'terraform check', 'terraform validate'] },
  { id: '1-18', domain: Domain.NPF, q: 'Ansible: Type of loop used with `loop` keyword?', a: 'Standard iteration (formerly with_items)', d: ['with_list', 'foreach', 'iterate'] },
  { id: '1-19', domain: Domain.NPF, q: 'Sync API: The client must do what?', a: 'Wait for the response before proceeding', d: ['Poll for status updates', 'Register a callback', 'Subscribe to events'] },
  { id: '1-20', domain: Domain.NPF, q: 'Git: Command to temporarily save changes without committing?', a: 'git stash', d: ['git save', 'git store', 'git cache'] },

  // --- 2.0 ACI ---
  { id: '2-1', domain: Domain.ACI, q: 'ACI API: URI to query a specific object by DN?', a: '/api/mo/<dn>.json', d: ['/api/class/<dn>.json', '/api/node/<dn>.json', '/api/dn/<dn>.json'] },
  { id: '2-2', domain: Domain.ACI, q: 'ACI API: URI to query all objects of a specific class?', a: '/api/class/<className>.json', d: ['/api/mo/<className>.json', '/api/objects/<className>.json', '/api/query/<className>.json'] },
  { id: '2-3', domain: Domain.ACI, q: 'ACI API: Query param to include child objects in response?', a: 'query-target=subtree', d: ['query-target=children', 'rsp-subtree=full', 'include=children'] },
  { id: '2-4', domain: Domain.ACI, q: 'ACI API: Query param to filter results based on property values?', a: 'query-target-filter', d: ['property-filter', 'rsp-filter', 'object-filter'] },
  { id: '2-5', domain: Domain.ACI, q: 'ACI Filter: Function to match exact string?', a: 'eq(item, "value")', d: ['match(item, "value")', 'exact(item, "value")', 'equals(item, "value")'] },
  { id: '2-6', domain: Domain.ACI, q: 'ACI Filter: Function to match partial string?', a: 'wcard(item, "val*")', d: ['like(item, "val*")', 'contains(item, "val")', 'match(item, "val*")'] },
  { id: '2-7', domain: Domain.ACI, q: 'Cobra SDK: Class used to authenticate?', a: 'LoginSession', d: ['AuthSession', 'ApicSession', 'UserSession'] },
  { id: '2-8', domain: Domain.ACI, q: 'Cobra SDK: Object that holds the MIT structure locally?', a: 'MoDirectory', d: ['MitTree', 'ObjectStore', 'LocalMit'] },
  { id: '2-9', domain: Domain.ACI, q: 'Cobra SDK: Method to commit changes to APIC?', a: 'commit(configRequest)', d: ['push(configRequest)', 'save(configRequest)', 'apply(configRequest)'] },
  { id: '2-10', domain: Domain.ACI, q: 'Cobra SDK: Method to find an object by its DN?', a: 'lookupByDn', d: ['queryByDn', 'findByDn', 'getByDn'] },
  { id: '2-11', domain: Domain.ACI, q: 'Ansible ACI: Module param for Application Profile?', a: 'ap', d: ['app_profile', 'application', 'profile'] },
  { id: '2-12', domain: Domain.ACI, q: 'Ansible ACI: Module param for Bridge Domain?', a: 'bd', d: ['bridge_domain', 'domain', 'bridge'] },
  { id: '2-13', domain: Domain.ACI, q: 'Ansible ACI: Relation parameter for Context (VRF)?', a: 'relation_fv_rs_ctx', d: ['vrf', 'context', 'relation_vrf'] },
  { id: '2-14', domain: Domain.ACI, q: 'Terraform ACI: Format for relation_fv_rs_cons?', a: 'List of strings (DNs)', d: ['Single string (DN)', 'Map of objects', 'Set of names'] },
  { id: '2-15', domain: Domain.ACI, q: 'Terraform ACI: Subnet notation requirement?', a: 'CIDR format (e.g., 10.0.0.1/24)', d: ['Dotted decimal only', 'Subnet mask format', 'Hex notation'] },
  { id: '2-16', domain: Domain.ACI, q: 'Tool: Built-in APIC tool to view API messages for GUI actions?', a: 'API Inspector', d: ['Visore', 'API Explorer', 'Object Browser'] },
  { id: '2-17', domain: Domain.ACI, q: 'Tool: Object Browser for ACI?', a: 'Visore', d: ['API Inspector', 'MO Explorer', 'Object Viewer'] },
  { id: '2-18', domain: Domain.ACI, q: 'ACI Class: Root class for a Tenant?', a: 'fvTenant', d: ['tnTenant', 'aciTenant', 'polTenant'] },
  { id: '2-19', domain: Domain.ACI, q: 'ACI Class: Class for a VRF?', a: 'fvCtx', d: ['fvVrf', 'l3Ctx', 'vrfInst'] },
  { id: '2-20', domain: Domain.ACI, q: 'ACI Class: Class for an EPG?', a: 'fvAEPg', d: ['fvEpg', 'fvEndpointGroup', 'epgInst'] },
  { id: '2-21', domain: Domain.ACI, q: 'ACI CNI: Main benefit for Kubernetes?', a: 'Maps K8s namespaces/pods to ACI EPGs', d: ['Provides container runtime', 'Manages K8s nodes', 'Replaces kube-proxy'] },
  { id: '2-22', domain: Domain.ACI, q: 'ACI API: Default format if not specified?', a: 'XML (usually, though JSON is preferred)', d: ['JSON', 'YAML', 'Plain text'] },
  { id: '2-23', domain: Domain.ACI, q: 'ACI API: Property to specify target subtree class?', a: 'target-subtree-class', d: ['subtree-class-filter', 'child-class', 'rsp-subtree-class'] },
  { id: '2-24', domain: Domain.ACI, q: 'Cobra: How to delete an MO?', a: 'mo.delete()', d: ['mo.remove()', 'directory.delete(mo)', 'mo.destroy()'] },
  { id: '2-25', domain: Domain.ACI, q: 'Ansible ACI: Typical state for deletion?', a: 'absent', d: ['deleted', 'removed', 'destroy'] },
  { id: '2-26', domain: Domain.ACI, q: 'Ansible ACI: Relation parameter for BD to VRF?', a: 'relation_fv_rs_ctx', d: ['vrf_name', 'bd_to_vrf', 'context_relation'] },
  { id: '2-27', domain: Domain.ACI, q: 'ACI Class: Relationship from EPG to BD?', a: 'fvRsBd', d: ['fvRsEpgBd', 'fvRelBd', 'epgRsBd'] },
  { id: '2-28', domain: Domain.ACI, q: 'ACI Class: Relationship from BD to VRF?', a: 'fvRsCtx', d: ['fvRsVrf', 'bdRsCtx', 'fvRelCtx'] },
  { id: '2-29', domain: Domain.ACI, q: 'ACI API: Filter logic for "NOT"?', a: 'not()', d: ['ne()', 'exclude()', '!()'] },
  { id: '2-30', domain: Domain.ACI, q: 'ACI API: Filter logic for "AND"?', a: 'and()', d: ['&&()', 'all()', 'both()'] },
  { id: '2-31', domain: Domain.ACI, q: 'Terraform ACI: Argument to set EPG description?', a: 'description', d: ['desc', 'descr', 'comment'] },
  { id: '2-32', domain: Domain.ACI, q: 'Cobra: Argument to specify parent MO during creation?', a: 'parentMoOrDn', d: ['parent', 'parentDn', 'parentObject'] },
  { id: '2-33', domain: Domain.ACI, q: 'Visore: Default URL path?', a: '/visore.html', d: ['/api/visore', '/apic/visore', '/inspector.html'] },
  { id: '2-34', domain: Domain.ACI, q: 'ACI Class: Physical Domain profile?', a: 'physDomP', d: ['phyDomain', 'l1DomP', 'infraDomP'] },
  { id: '2-35', domain: Domain.ACI, q: 'ACI Class: VLAN Pool?', a: 'fvnsVlanInstP', d: ['vlanPool', 'fvVlanPool', 'infraVlanP'] },
  { id: '2-36', domain: Domain.ACI, q: 'Ansible: Module for generic ACI REST calls?', a: 'aci_rest', d: ['aci_api', 'aci_request', 'aci_raw'] },
  { id: '2-37', domain: Domain.ACI, q: 'ACI API: Status code for successful login?', a: '200 OK', d: ['201 Created', '204 No Content', '202 Accepted'] },
  { id: '2-38', domain: Domain.ACI, q: 'ACI: Logical container for policies?', a: 'Tenant', d: ['Fabric', 'Pod', 'Domain'] },
  { id: '2-39', domain: Domain.ACI, q: 'Cobra: Python package name?', a: 'acicobra', d: ['cobra', 'cisco-cobra', 'aci-sdk'] },
  { id: '2-40', domain: Domain.ACI, q: 'Terraform: Provider name for ACI?', a: 'CiscoDevNet/aci', d: ['cisco/aci', 'hashicorp/aci', 'aci/terraform'] },

  // --- 3.0 NX-OS ---
  { id: '3-1', domain: Domain.NXOS, q: 'POAP: Script must be written in?', a: 'Python (or TCL)', d: ['Bash', 'Perl', 'Ruby'] },
  { id: '3-2', domain: Domain.NXOS, q: 'POAP: Top of script requirement to import CLI functions?', a: 'from cli import *', d: ['import cli', 'from nxos import cli', 'import nxapi'] },
  { id: '3-3', domain: Domain.NXOS, q: 'NX-OS Python: Function to run CLI and return raw string?', a: 'cli()', d: ['clid()', 'clip()', 'clis()'] },
  { id: '3-4', domain: Domain.NXOS, q: 'NX-OS Python: Function to run CLI and return JSON/Dict?', a: 'clid()', d: ['cli()', 'clip()', 'clij()'] },
  { id: '3-5', domain: Domain.NXOS, q: 'NX-OS Python: Function to run CLI and print directly to stdout?', a: 'clip()', d: ['cli()', 'clid()', 'clio()'] },
  { id: '3-6', domain: Domain.NXOS, q: 'Guest Shell: Command to execute command on host switch?', a: 'dohost', d: ['runhost', 'nxcli', 'switchcmd'] },
  { id: '3-7', domain: Domain.NXOS, q: 'Guest Shell: Native shell type?', a: 'Bash (CentOS based)', d: ['Zsh (Ubuntu based)', 'Sh (Alpine based)', 'Fish (Debian based)'] },
  { id: '3-8', domain: Domain.NXOS, q: 'EEM: Action to execute a config command?', a: 'action <n> cli command "<cmd>"', d: ['action <n> exec "<cmd>"', 'action <n> run "<cmd>"', 'action <n> config "<cmd>"'] },
  { id: '3-9', domain: Domain.NXOS, q: 'NX-API CLI: Message format type for show commands?', a: 'cli_show', d: ['cli_exec', 'cli_display', 'show_cmd'] },
  { id: '3-10', domain: Domain.NXOS, q: 'NX-API CLI: Message format type for config commands?', a: 'cli_conf', d: ['cli_config', 'conf_cmd', 'cli_set'] },
  { id: '3-11', domain: Domain.NXOS, q: 'NX-API REST: URL path for DME access?', a: '/api/mo/', d: ['/api/dme/', '/ins/api/', '/rest/mo/'] },
  { id: '3-12', domain: Domain.NXOS, q: 'NETCONF: Port number?', a: '830', d: ['22', '443', '8443'] },
  { id: '3-13', domain: Domain.NXOS, q: 'NETCONF: Operation to change configuration?', a: 'edit-config', d: ['set-config', 'modify-config', 'update-config'] },
  { id: '3-14', domain: Domain.NXOS, q: 'NETCONF: Operation to retrieve running config?', a: 'get-config', d: ['read-config', 'fetch-config', 'show-config'] },
  { id: '3-15', domain: Domain.NXOS, q: 'NETCONF: Default edit operation (merge/replace/none)?', a: 'merge', d: ['replace', 'none', 'create'] },
  { id: '3-16', domain: Domain.NXOS, q: 'gNMI: Supported encoding formats?', a: 'JSON, Bytes (Protobuf)', d: ['XML, YAML', 'JSON, XML', 'YAML, Protobuf'] },
  { id: '3-17', domain: Domain.NXOS, q: 'gNMI: RPC to stream data?', a: 'Subscribe', d: ['Stream', 'Watch', 'Listen'] },
  { id: '3-18', domain: Domain.NXOS, q: 'Telemetry: "Dial-out" means?', a: 'Device initiates connection to collector', d: ['Collector initiates connection to device', 'Device polls collector', 'Push via SNMP trap'] },
  { id: '3-19', domain: Domain.NXOS, q: 'Telemetry: "Dial-in" means?', a: 'Collector initiates connection to device', d: ['Device initiates connection to collector', 'Collector polls device', 'Device sends SNMP trap'] },
  { id: '3-20', domain: Domain.NXOS, q: 'NX-OS Telemetry: Interval unit?', a: 'Milliseconds', d: ['Seconds', 'Minutes', 'Microseconds'] },
  { id: '3-21', domain: Domain.NXOS, q: 'YANG: Google-defined vendor-neutral models?', a: 'OpenConfig', d: ['IETF', 'Native', 'Cisco-common'] },
  { id: '3-22', domain: Domain.NXOS, q: 'YANG: Cisco specific models?', a: 'Native', d: ['OpenConfig', 'IETF', 'Vendor'] },
  { id: '3-23', domain: Domain.NXOS, q: 'NX-API: Default HTTP port?', a: '80', d: ['8080', '443', '8443'] },
  { id: '3-24', domain: Domain.NXOS, q: 'NX-API: Default HTTPS port?', a: '443', d: ['8443', '8080', '9443'] },
  { id: '3-25', domain: Domain.NXOS, q: 'NX-API: Sandbox URL?', a: '/ins', d: ['/api', '/sandbox', '/nxapi'] },
  { id: '3-26', domain: Domain.NXOS, q: 'NETCONF: Filter type to select specific nodes?', a: 'subtree', d: ['xpath', 'path', 'node'] },
  { id: '3-27', domain: Domain.NXOS, q: 'EEM: Event detector for syslog?', a: 'event syslog', d: ['event log', 'event message', 'event alert'] },
  { id: '3-28', domain: Domain.NXOS, q: 'EEM: Event detector for CLI command?', a: 'event cli match', d: ['event command', 'event exec', 'event input'] },
  { id: '3-29', domain: Domain.NXOS, q: 'Guest Shell: Packet manager?', a: 'yum', d: ['apt', 'pip', 'dnf'] },
  { id: '3-30', domain: Domain.NXOS, q: 'NX-OS Python: How to separate multiple commands in one string?', a: ' ; (semicolon)', d: [' && (double ampersand)', ' | (pipe)', ' \\n (newline)'] },
  { id: '3-31', domain: Domain.NXOS, q: 'Model Driven Telemetry: Encoding using Key/Value pairs?', a: 'GPB-KV (Google Protobuf Key Value)', d: ['GPB (Google Protobuf)', 'JSON', 'CBOR'] },
  { id: '3-32', domain: Domain.NXOS, q: 'Model Driven Telemetry: Compact encoding?', a: 'GPB (Google Protobuf)', d: ['GPB-KV (Google Protobuf Key Value)', 'JSON-compact', 'MessagePack'] },
  { id: '3-33', domain: Domain.NXOS, q: 'NETCONF: Python library often used?', a: 'ncclient', d: ['netconf', 'pynetconf', 'cisco-netconf'] },
  { id: '3-34', domain: Domain.NXOS, q: 'NX-API REST: Payload format?', a: 'JSON or XML', d: ['JSON only', 'XML only', 'YAML or JSON'] },
  { id: '3-35', domain: Domain.NXOS, q: 'NX-OS: Feature to enable API?', a: 'feature nxapi', d: ['feature restapi', 'feature api', 'feature http-api'] },
  { id: '3-36', domain: Domain.NXOS, q: 'NX-OS: Feature to enable NETCONF?', a: 'feature netconf', d: ['feature ssh', 'feature xml-agent', 'feature yang'] },
  { id: '3-37', domain: Domain.NXOS, q: 'NX-OS: Feature to enable Bash?', a: 'feature bash-shell', d: ['feature bash', 'feature shell', 'feature linux-shell'] },
  { id: '3-38', domain: Domain.NXOS, q: 'gNMI: Transport protocol?', a: 'HTTP/2 (gRPC)', d: ['HTTP/1.1', 'TCP', 'WebSocket'] },
  { id: '3-39', domain: Domain.NXOS, q: 'POAP: DHCP option for script URI?', a: 'Option 66/67', d: ['Option 43', 'Option 150', 'Option 82'] },
  { id: '3-40', domain: Domain.NXOS, q: 'YANG: Leaf node constraint?', a: 'must', d: ['when', 'require', 'assert'] },
  { id: '3-41', domain: Domain.NXOS, q: 'NX-API CLI: Response format for cli_show_ascii?', a: 'Raw text output (not structured)', d: ['JSON formatted output', 'XML formatted output', 'Binary encoded output'] },
  { id: '3-42', domain: Domain.NXOS, q: 'NX-API CLI: Which message type returns structured data?', a: 'cli_show (JSON/XML)', d: ['cli_show_ascii', 'cli_conf', 'bash'] },
  { id: '3-43', domain: Domain.NXOS, q: 'NX-API REST: DME root class for system?', a: 'topSystem', d: ['sysRoot', 'nxosSystem', 'topRoot'] },
  { id: '3-44', domain: Domain.NXOS, q: 'NX-API REST: Query param to filter by property?', a: 'query-target-filter', d: ['rsp-prop-filter', 'property-filter', 'object-filter'] },
  { id: '3-45', domain: Domain.NXOS, q: 'NX-API REST: Query param to include children?', a: 'rsp-subtree=children', d: ['query-target=children', 'include-children=true', 'rsp-subtree=full'] },
  { id: '3-46', domain: Domain.NXOS, q: 'DME: What does DME stand for?', a: 'Data Management Engine', d: ['Device Management Entity', 'Dynamic Model Engine', 'Data Model Environment'] },
  { id: '3-47', domain: Domain.NXOS, q: 'DME: Class for physical interfaces?', a: 'l1PhysIf', d: ['ethpmPhysIf', 'ifPhys', 'l2If'] },
  { id: '3-48', domain: Domain.NXOS, q: 'DME: Class for VLAN?', a: 'l2BD (Bridge Domain)', d: ['vlanEntity', 'l2Vlan', 'sviIf'] },
  { id: '3-49', domain: Domain.NXOS, q: 'DME: Class for BGP instance?', a: 'bgpInst', d: ['bgpEntity', 'bgpDom', 'bgpProc'] },
  { id: '3-50', domain: Domain.NXOS, q: 'DME: Class for OSPF instance?', a: 'ospfInst', d: ['ospfEntity', 'ospfDom', 'ospfProc'] },
  { id: '3-51', domain: Domain.NXOS, q: 'NETCONF: XML namespace for NX-OS native models?', a: 'http://cisco.com/ns/yang/cisco-nx-os-device', d: ['urn:ietf:params:xml:ns:yang:nxos', 'http://cisco.com/yang/nxos', 'urn:cisco:params:xml:ns:nxos'] },
  { id: '3-52', domain: Domain.NXOS, q: 'NETCONF: Operation to lock configuration datastore?', a: 'lock', d: ['lock-config', 'acquire-lock', 'exclusive'] },
  { id: '3-53', domain: Domain.NXOS, q: 'NETCONF: Operation to unlock configuration datastore?', a: 'unlock', d: ['release-lock', 'unlock-config', 'free'] },
  { id: '3-54', domain: Domain.NXOS, q: 'NETCONF: Operation to retrieve operational and config data?', a: 'get', d: ['get-config', 'get-all', 'retrieve'] },
  { id: '3-55', domain: Domain.NXOS, q: 'NETCONF: Message to close session gracefully?', a: 'close-session', d: ['disconnect', 'end-session', 'terminate'] },
  { id: '3-56', domain: Domain.NXOS, q: 'NETCONF: Message to forcefully terminate session?', a: 'kill-session', d: ['terminate-session', 'abort-session', 'force-close'] },
  { id: '3-57', domain: Domain.NXOS, q: 'NETCONF: Attribute to delete a configuration element?', a: 'operation="delete"', d: ['operation="remove"', 'action="delete"', 'nc:operation="remove"'] },
  { id: '3-58', domain: Domain.NXOS, q: 'NETCONF: Attribute to replace entire configuration block?', a: 'operation="replace"', d: ['operation="overwrite"', 'operation="set"', 'action="replace"'] },
  { id: '3-59', domain: Domain.NXOS, q: 'ncclient: Method to connect to device?', a: 'manager.connect()', d: ['manager.open()', 'session.connect()', 'ncclient.connect()'] },
  { id: '3-60', domain: Domain.NXOS, q: 'ncclient: Parameter to ignore SSH host key?', a: 'hostkey_verify=False', d: ['verify_host=False', 'ssh_hostkey_check=False', 'ignore_hostkey=True'] },
  { id: '3-61', domain: Domain.NXOS, q: 'ncclient: Parameter to specify device type?', a: 'device_params={"name": "nexus"}', d: ['device_type="nexus"', 'platform="nxos"', 'vendor="cisco-nxos"'] },
  { id: '3-62', domain: Domain.NXOS, q: 'RESTCONF: Default HTTP port?', a: '443 (HTTPS)', d: ['80 (HTTP)', '8080', '8443'] },
  { id: '3-63', domain: Domain.NXOS, q: 'RESTCONF: Base URL path?', a: '/restconf/data/', d: ['/api/restconf/', '/restconf/api/', '/data/restconf/'] },
  { id: '3-64', domain: Domain.NXOS, q: 'RESTCONF: Content-Type header for JSON?', a: 'application/yang-data+json', d: ['application/json', 'application/restconf+json', 'text/json'] },
  { id: '3-65', domain: Domain.NXOS, q: 'RESTCONF: HTTP method for PATCH vs PUT?', a: 'PATCH=partial update, PUT=replace', d: ['PATCH=replace, PUT=partial update', 'PATCH=create, PUT=update', 'PATCH=merge, PUT=create'] },
  { id: '3-66', domain: Domain.NXOS, q: 'RESTCONF: Discovery endpoint for root resources?', a: '/.well-known/host-meta', d: ['/restconf/capabilities', '/restconf/discovery', '/.well-known/restconf'] },
  { id: '3-67', domain: Domain.NXOS, q: 'gNMI: RPC to retrieve configuration/state?', a: 'Get', d: ['Read', 'Fetch', 'Query'] },
  { id: '3-68', domain: Domain.NXOS, q: 'gNMI: RPC to modify configuration?', a: 'Set', d: ['Update', 'Configure', 'Put'] },
  { id: '3-69', domain: Domain.NXOS, q: 'gNMI: RPC to get supported models?', a: 'Capabilities', d: ['GetModels', 'Schema', 'Discover'] },
  { id: '3-70', domain: Domain.NXOS, q: 'gNMI: Subscribe mode for periodic updates?', a: 'SAMPLE', d: ['POLL', 'PERIODIC', 'INTERVAL'] },
  { id: '3-71', domain: Domain.NXOS, q: 'gNMI: Subscribe mode for change-based updates?', a: 'ON_CHANGE', d: ['STREAM', 'EVENT', 'TRIGGER'] },
  { id: '3-72', domain: Domain.NXOS, q: 'gNMI: Subscribe mode for one-time snapshot?', a: 'ONCE', d: ['POLL', 'SINGLE', 'SNAPSHOT'] },
  { id: '3-73', domain: Domain.NXOS, q: 'gNMI: Path separator character?', a: '/', d: ['.', ':', '\\\\'] },
  { id: '3-74', domain: Domain.NXOS, q: 'gNMI: What specifies a list key in path?', a: '[key=value]', d: ['{key:value}', '(key=value)', '<key=value>'] },
  { id: '3-75', domain: Domain.NXOS, q: 'EEM: Keyword to define applet?', a: 'event manager applet <name>', d: ['eem applet <name>', 'event applet <name>', 'event manager script <name>'] },
  { id: '3-76', domain: Domain.NXOS, q: 'EEM: Event type for periodic execution?', a: 'event timer cron', d: ['event timer periodic', 'event schedule', 'event timer interval'] },
  { id: '3-77', domain: Domain.NXOS, q: 'EEM: Event type for interface state change?', a: 'event track', d: ['event interface', 'event link', 'event intf-status'] },
  { id: '3-78', domain: Domain.NXOS, q: 'EEM: Event type for counter threshold?', a: 'event counter', d: ['event threshold', 'event snmp', 'event metric'] },
  { id: '3-79', domain: Domain.NXOS, q: 'EEM: Action to run Python script?', a: 'action <n> cli command "python <script>"', d: ['action <n> python <script>', 'action <n> script python <script>', 'action <n> exec python <script>'] },
  { id: '3-80', domain: Domain.NXOS, q: 'EEM: Action to send syslog message?', a: 'action <n> syslog priority <level> msg "<text>"', d: ['action <n> log <level> "<text>"', 'action <n> send-syslog <level> "<text>"', 'action <n> message syslog <level> "<text>"'] },
  { id: '3-81', domain: Domain.NXOS, q: 'Scheduler: Command to create a job?', a: 'scheduler job name <name>', d: ['scheduler create job <name>', 'job scheduler <name>', 'scheduler add job <name>'] },
  { id: '3-82', domain: Domain.NXOS, q: 'Scheduler: Command to define execution time?', a: 'scheduler schedule name <name>', d: ['scheduler time <name>', 'scheduler trigger <name>', 'schedule define <name>'] },
  { id: '3-83', domain: Domain.NXOS, q: 'Scheduler: Keyword for recurring schedule?', a: 'time daily <HH:MM>', d: ['time recurring <HH:MM>', 'time repeat <HH:MM>', 'time periodic <HH:MM>'] },
  { id: '3-84', domain: Domain.NXOS, q: 'Scheduler: Command to associate job with schedule?', a: 'job name <job>', d: ['assign job <job>', 'run job <job>', 'execute job <job>'] },
  { id: '3-85', domain: Domain.NXOS, q: 'POAP: File that contains MD5 hash of script?', a: '<script_name>.md5', d: ['<script_name>.hash', '<script_name>.checksum', 'md5sum.txt'] },
  { id: '3-86', domain: Domain.NXOS, q: 'POAP: Protocol options for downloading script?', a: 'TFTP, HTTP, HTTPS, SCP, FTP', d: ['TFTP, HTTP only', 'TFTP, FTP, NFS', 'HTTP, HTTPS, SFTP only'] },
  { id: '3-87', domain: Domain.NXOS, q: 'POAP: Function to copy file from server?', a: 'poap.copy_file()', d: ['poap.download()', 'poap.fetch_file()', 'poap.transfer()'] },
  { id: '3-88', domain: Domain.NXOS, q: 'POAP: Function to set boot variable?', a: 'poap.set_boot_image()', d: ['poap.set_bootvar()', 'poap.configure_boot()', 'poap.boot_image()'] },
  { id: '3-89', domain: Domain.NXOS, q: 'Guest Shell: Command to enable?', a: 'guestshell enable', d: ['feature guestshell', 'guestshell activate', 'enable guestshell'] },
  { id: '3-90', domain: Domain.NXOS, q: 'Guest Shell: Command to enter?', a: 'guestshell', d: ['run guestshell', 'guestshell run bash', 'enter guestshell'] },
  { id: '3-91', domain: Domain.NXOS, q: 'Guest Shell: Path to access bootflash?', a: '/bootflash', d: ['/mnt/bootflash', '/flash', '/vol/bootflash'] },
  { id: '3-92', domain: Domain.NXOS, q: 'Guest Shell: Network namespace for management?', a: 'management', d: ['default', 'mgmt', 'global'] },
  { id: '3-93', domain: Domain.NXOS, q: 'Guest Shell: Command to run in specific VRF?', a: 'chvrf <vrf> <command>', d: ['ip vrf exec <vrf> <command>', 'vrf <vrf> run <command>', 'setvrf <vrf> <command>'] },
  { id: '3-94', domain: Domain.NXOS, q: 'Telemetry: Command to create sensor group?', a: 'sensor-group <id>', d: ['telemetry sensor <id>', 'sensor <id>', 'create sensor-group <id>'] },
  { id: '3-95', domain: Domain.NXOS, q: 'Telemetry: Command to create destination group?', a: 'destination-group <id>', d: ['telemetry destination <id>', 'collector-group <id>', 'dest-group <id>'] },
  { id: '3-96', domain: Domain.NXOS, q: 'Telemetry: Command to create subscription?', a: 'subscription <id>', d: ['telemetry subscription <id>', 'subscribe <id>', 'sensor-subscription <id>'] },
  { id: '3-97', domain: Domain.NXOS, q: 'Telemetry: Keyword to specify DME path?', a: 'path sys/...', d: ['dme-path sys/...', 'sensor-path sys/...', 'data-source sys/...'] },
  { id: '3-98', domain: Domain.NXOS, q: 'Telemetry: Transport protocol options?', a: 'gRPC, HTTP, UDP', d: ['TCP, HTTP, HTTPS', 'gRPC, HTTPS only', 'UDP, TCP, gRPC'] },
  { id: '3-99', domain: Domain.NXOS, q: 'YANG: Keyword for reusable structure?', a: 'grouping', d: ['typedef', 'container', 'template'] },
  { id: '3-100', domain: Domain.NXOS, q: 'YANG: Keyword to include a grouping?', a: 'uses', d: ['include', 'import', 'apply'] },

  // --- 4.0 UCS/Intersight ---
  { id: '4-1', domain: Domain.UCS, q: 'UCS Python SDK: Function to add an MO?', a: 'add_mo', d: ['create_mo', 'insert_mo', 'new_mo'] },
  { id: '4-2', domain: Domain.UCS, q: 'UCS Python SDK: Argument to update if exists?', a: 'modify_present=True', d: ['update_existing=True', 'overwrite=True', 'upsert=True'] },
  { id: '4-3', domain: Domain.UCS, q: 'UCS Python SDK: Is there a set_mo function?', a: 'No (use add_mo with modify_present)', d: ['Yes (set_mo)', 'Yes (update_mo)', 'Yes (modify_mo)'] },
  { id: '4-4', domain: Domain.UCS, q: 'LsServer: Type for a Service Profile Template?', a: 'initial-template / updating-template', d: ['template', 'instance', 'derived'] },
  { id: '4-5', domain: Domain.UCS, q: 'LsServer: Type for a Service Profile Instance?', a: 'instance', d: ['template', 'derived', 'deployed'] },
  { id: '4-6', domain: Domain.UCS, q: 'PowerTool: Pattern to modify objects?', a: 'Get-UcsX | Set-UcsX', d: ['Find-UcsX | Update-UcsX', 'Select-UcsX | Modify-UcsX', 'Query-UcsX | Change-UcsX'] },
  { id: '4-7', domain: Domain.UCS, q: 'PowerTool: Flag to confirm XML output?', a: '-Xml', d: ['-Format Xml', '-OutputXml', '-AsXml'] },
  { id: '4-8', domain: Domain.UCS, q: 'Intersight Auth: Hashing algorithm for body?', a: 'SHA256', d: ['SHA512', 'MD5', 'SHA1'] },
  { id: '4-9', domain: Domain.UCS, q: 'Intersight Auth: Signature algorithm?', a: 'RSA', d: ['HMAC', 'ECDSA', 'DSA'] },
  { id: '4-10', domain: Domain.UCS, q: 'Intersight API: Mandatory relationship for most resources?', a: 'Organization', d: ['Account', 'Tenant', 'Project'] },
  { id: '4-11', domain: Domain.UCS, q: 'Intersight API: Organization reference requires?', a: 'moid and object_type', d: ['name only', 'dn only', 'uuid and name'] },
  { id: '4-12', domain: Domain.UCS, q: 'Terraform Intersight: Authentication requires?', a: 'apikey and secretkey (file)', d: ['username and password', 'token only', 'certificate and key'] },
  { id: '4-13', domain: Domain.UCS, q: 'UCS Python SDK: Module to import?', a: 'ucsmsdk', d: ['ucssdk', 'cisco_ucs', 'pyucs'] },
  { id: '4-14', domain: Domain.UCS, q: 'UCS Manager: XML API endpoint?', a: '/nuova', d: ['/api', '/xmlapi', '/ucsm'] },
  { id: '4-15', domain: Domain.UCS, q: 'Intersight: Query parameter to filter?', a: '$filter', d: ['$query', '$where', '$match'] },
  { id: '4-16', domain: Domain.UCS, q: 'Intersight: Query parameter to select specific fields?', a: '$select', d: ['$fields', '$include', '$columns'] },
  { id: '4-17', domain: Domain.UCS, q: 'UCS Class: Compute Blade?', a: 'computeBlade', d: ['bladeSrvr', 'ucsBlade', 'serverBlade'] },
  { id: '4-18', domain: Domain.UCS, q: 'UCS Class: Rack Unit?', a: 'computeRackUnit', d: ['rackServer', 'ucsRack', 'serverRack'] },
  { id: '4-19', domain: Domain.UCS, q: 'Intersight: Header containing the signature?', a: 'Authorization', d: ['X-Signature', 'Signature', 'X-Auth-Signature'] },
  { id: '4-20', domain: Domain.UCS, q: 'Intersight: Header containing the date?', a: 'Date (or X-Date)', d: ['X-Timestamp', 'Request-Date', 'X-Request-Time'] },
  { id: '4-21', domain: Domain.UCS, q: 'UCS Python SDK: Login handle class?', a: 'UcsHandle', d: ['UcsSession', 'UcsConnection', 'UcsLogin'] },
  { id: '4-22', domain: Domain.UCS, q: 'PowerTool: Cmdlet to connect?', a: 'Connect-Ucs', d: ['New-UcsSession', 'Open-Ucs', 'Start-UcsConnection'] },
  { id: '4-23', domain: Domain.UCS, q: 'PowerTool: Cmdlet to disconnect?', a: 'Disconnect-Ucs', d: ['Close-Ucs', 'Remove-UcsSession', 'Stop-UcsConnection'] },
  { id: '4-24', domain: Domain.UCS, q: 'Intersight: Object Type for physical server?', a: 'compute.PhysicalSummary', d: ['server.Physical', 'compute.Server', 'hardware.Server'] },
  { id: '4-25', domain: Domain.UCS, q: 'Intersight: Object Type for organization?', a: 'organization.Organization', d: ['iam.Organization', 'resource.Organization', 'tenant.Organization'] },
  { id: '4-26', domain: Domain.UCS, q: 'Terraform Intersight: Provider name?', a: 'CiscoDevNet/intersight', d: ['cisco/intersight', 'hashicorp/intersight', 'intersight/terraform'] },
  { id: '4-27', domain: Domain.UCS, q: 'UCS Python: Query class objects?', a: 'handle.query_classid("classId")', d: ['handle.get_class("classId")', 'handle.find_classid("classId")', 'handle.search_class("classId")'] },
  { id: '4-28', domain: Domain.UCS, q: 'UCS Python: Commit transaction?', a: 'handle.commit()', d: ['handle.save()', 'handle.apply()', 'handle.push()'] },
  { id: '4-29', domain: Domain.UCS, q: 'UCS Python: Logout?', a: 'handle.logout()', d: ['handle.disconnect()', 'handle.close()', 'handle.end()'] },
  { id: '4-30', domain: Domain.UCS, q: 'Intersight API: Base URL?', a: 'https://intersight.com/api/v1', d: ['https://api.intersight.com/v1', 'https://intersight.cisco.com/api', 'https://cloud.intersight.com/api/v1'] },
];
