import { Question, Domain } from './types';

export const questions: Question[] = [
  // --- 1.0 Network Programmability Foundation ---
  { id: '1-1', domain: Domain.NPF, q: 'Git: Command to unstage a file but keep changes in working directory?', a: 'git reset HEAD <file>' },
  { id: '1-2', domain: Domain.NPF, q: 'Git: Command to undo the last commit and keep changes staged?', a: 'git reset --soft HEAD~1' },
  { id: '1-3', domain: Domain.NPF, q: 'Git: Command to completely discard all local changes in working directory?', a: 'git reset --hard' },
  { id: '1-4', domain: Domain.NPF, q: 'Git: Applies changes from a specific commit to current branch?', a: 'git cherry-pick <commit-hash>' },
  { id: '1-5', domain: Domain.NPF, q: 'Git: Command to create a new branch and switch to it immediately?', a: 'git checkout -b <branch-name>' },
  { id: '1-6', domain: Domain.NPF, q: 'REST vs RPC: Which typically uses a single URI endpoint for multiple actions?', a: 'RPC' },
  { id: '1-7', domain: Domain.NPF, q: 'REST vs RPC: Which is resource-centric?', a: 'REST' },
  { id: '1-8', domain: Domain.NPF, q: 'Async API: What HTTP status code typically indicates "Accepted/Processing"?', a: '202 Accepted' },
  { id: '1-9', domain: Domain.NPF, q: 'Python: Mutable data type defined with square brackets []?', a: 'List' },
  { id: '1-10', domain: Domain.NPF, q: 'Python: Immutable data type defined with parentheses ()?', a: 'Tuple' },
  { id: '1-11', domain: Domain.NPF, q: 'Python: Unordered collection of unique elements?', a: 'Set' },
  { id: '1-12', domain: Domain.NPF, q: 'Python: Syntax to define a class method?', a: 'def method_name(self):' },
  { id: '1-13', domain: Domain.NPF, q: 'Python: Library used for standard HTTP requests?', a: 'requests' },
  { id: '1-14', domain: Domain.NPF, q: 'Python: Command to create a virtual environment?', a: 'python3 -m venv <dir>' },
  { id: '1-15', domain: Domain.NPF, q: 'Terraform: What file tracks the current state of infrastructure?', a: 'terraform.tfstate' },
  { id: '1-16', domain: Domain.NPF, q: 'Ansible: What format are Playbooks written in?', a: 'YAML' },
  { id: '1-17', domain: Domain.NPF, q: 'Terraform: Command to preview changes before applying?', a: 'terraform plan' },
  { id: '1-18', domain: Domain.NPF, q: 'Ansible: Type of loop used with `loop` keyword?', a: 'Standard iteration (formerly with_items)' },
  { id: '1-19', domain: Domain.NPF, q: 'Sync API: The client must do what?', a: 'Wait for the response before proceeding' },
  { id: '1-20', domain: Domain.NPF, q: 'Git: Command to temporarily save changes without committing?', a: 'git stash' },

  // --- 2.0 ACI ---
  { id: '2-1', domain: Domain.ACI, q: 'ACI API: URI to query a specific object by DN?', a: '/api/mo/<dn>.json' },
  { id: '2-2', domain: Domain.ACI, q: 'ACI API: URI to query all objects of a specific class?', a: '/api/class/<className>.json' },
  { id: '2-3', domain: Domain.ACI, q: 'ACI API: Query param to include child objects in response?', a: 'query-target=subtree' },
  { id: '2-4', domain: Domain.ACI, q: 'ACI API: Query param to filter results based on property values?', a: 'query-target-filter' },
  { id: '2-5', domain: Domain.ACI, q: 'ACI Filter: Function to match exact string?', a: 'eq(item, "value")' },
  { id: '2-6', domain: Domain.ACI, q: 'ACI Filter: Function to match partial string?', a: 'wcard(item, "val*")' },
  { id: '2-7', domain: Domain.ACI, q: 'Cobra SDK: Class used to authenticate?', a: 'LoginSession' },
  { id: '2-8', domain: Domain.ACI, q: 'Cobra SDK: Object that holds the MIT structure locally?', a: 'MoDirectory' },
  { id: '2-9', domain: Domain.ACI, q: 'Cobra SDK: Method to commit changes to APIC?', a: 'commit(configRequest)' },
  { id: '2-10', domain: Domain.ACI, q: 'Cobra SDK: Method to find an object by its DN?', a: 'lookupByDn' },
  { id: '2-11', domain: Domain.ACI, q: 'Ansible ACI: Module param for Application Profile?', a: 'ap' },
  { id: '2-12', domain: Domain.ACI, q: 'Ansible ACI: Module param for Bridge Domain?', a: 'bd' },
  { id: '2-13', domain: Domain.ACI, q: 'Ansible ACI: Relation parameter for Context (VRF)?', a: 'relation_fv_rs_ctx' },
  { id: '2-14', domain: Domain.ACI, q: 'Terraform ACI: Format for relation_fv_rs_cons?', a: 'List of strings (DNs)' },
  { id: '2-15', domain: Domain.ACI, q: 'Terraform ACI: Subnet notation requirement?', a: 'CIDR format (e.g., 10.0.0.1/24)' },
  { id: '2-16', domain: Domain.ACI, q: 'Tool: Built-in APIC tool to view API messages for GUI actions?', a: 'API Inspector' },
  { id: '2-17', domain: Domain.ACI, q: 'Tool: Object Browser for ACI?', a: 'Visore' },
  { id: '2-18', domain: Domain.ACI, q: 'ACI Class: Root class for a Tenant?', a: 'fvTenant' },
  { id: '2-19', domain: Domain.ACI, q: 'ACI Class: Class for a VRF?', a: 'fvCtx' },
  { id: '2-20', domain: Domain.ACI, q: 'ACI Class: Class for an EPG?', a: 'fvAEPg' },
  { id: '2-21', domain: Domain.ACI, q: 'ACI CNI: Main benefit for Kubernetes?', a: 'Maps K8s namespaces/pods to ACI EPGs' },
  { id: '2-22', domain: Domain.ACI, q: 'ACI API: Default format if not specified?', a: 'XML (usually, though JSON is preferred)' },
  { id: '2-23', domain: Domain.ACI, q: 'ACI API: Property to specify target subtree class?', a: 'target-subtree-class' },
  { id: '2-24', domain: Domain.ACI, q: 'Cobra: How to delete an MO?', a: 'mo.delete()' },
  { id: '2-25', domain: Domain.ACI, q: 'Ansible ACI: Typical state for deletion?', a: 'absent' },
  { id: '2-26', domain: Domain.ACI, q: 'Ansible ACI: Relation parameter for BD to VRF?', a: 'relation_fv_rs_ctx' },
  { id: '2-27', domain: Domain.ACI, q: 'ACI Class: Relationship from EPG to BD?', a: 'fvRsBd' },
  { id: '2-28', domain: Domain.ACI, q: 'ACI Class: Relationship from BD to VRF?', a: 'fvRsCtx' },
  { id: '2-29', domain: Domain.ACI, q: 'ACI API: Filter logic for "NOT"?', a: 'not()' },
  { id: '2-30', domain: Domain.ACI, q: 'ACI API: Filter logic for "AND"?', a: 'and()' },
  { id: '2-31', domain: Domain.ACI, q: 'Terraform ACI: Argument to set EPG description?', a: 'description' },
  { id: '2-32', domain: Domain.ACI, q: 'Cobra: Argument to specify parent MO during creation?', a: 'parentMoOrDn' },
  { id: '2-33', domain: Domain.ACI, q: 'Visore: Default URL path?', a: '/visore.html' },
  { id: '2-34', domain: Domain.ACI, q: 'ACI Class: Physical Domain profile?', a: 'physDomP' },
  { id: '2-35', domain: Domain.ACI, q: 'ACI Class: VLAN Pool?', a: 'fvnsVlanInstP' },
  { id: '2-36', domain: Domain.ACI, q: 'Ansible: Module for generic ACI REST calls?', a: 'aci_rest' },
  { id: '2-37', domain: Domain.ACI, q: 'ACI API: Status code for successful login?', a: '200 OK' },
  { id: '2-38', domain: Domain.ACI, q: 'ACI: Logical container for policies?', a: 'Tenant' },
  { id: '2-39', domain: Domain.ACI, q: 'Cobra: Python package name?', a: 'acicobra' },
  { id: '2-40', domain: Domain.ACI, q: 'Terraform: Provider name for ACI?', a: 'CiscoDevNet/aci' },

  // --- 3.0 NX-OS ---
  { id: '3-1', domain: Domain.NXOS, q: 'POAP: Script must be written in?', a: 'Python (or TCL)' },
  { id: '3-2', domain: Domain.NXOS, q: 'POAP: Top of script requirement to import CLI functions?', a: 'from cli import *' },
  { id: '3-3', domain: Domain.NXOS, q: 'NX-OS Python: Function to run CLI and return raw string?', a: 'cli()' },
  { id: '3-4', domain: Domain.NXOS, q: 'NX-OS Python: Function to run CLI and return JSON/Dict?', a: 'clid()' },
  { id: '3-5', domain: Domain.NXOS, q: 'NX-OS Python: Function to run CLI and print directly to stdout?', a: 'clip()' },
  { id: '3-6', domain: Domain.NXOS, q: 'Guest Shell: Command to execute command on host switch?', a: 'dohost' },
  { id: '3-7', domain: Domain.NXOS, q: 'Guest Shell: Native shell type?', a: 'Bash (CentOS based)' },
  { id: '3-8', domain: Domain.NXOS, q: 'EEM: Action to execute a config command?', a: 'action <n> cli command "<cmd>"' },
  { id: '3-9', domain: Domain.NXOS, q: 'NX-API CLI: Message format type for show commands?', a: 'cli_show' },
  { id: '3-10', domain: Domain.NXOS, q: 'NX-API CLI: Message format type for config commands?', a: 'cli_conf' },
  { id: '3-11', domain: Domain.NXOS, q: 'NX-API REST: URL path for DME access?', a: '/api/mo/' },
  { id: '3-12', domain: Domain.NXOS, q: 'NETCONF: Port number?', a: '830' },
  { id: '3-13', domain: Domain.NXOS, q: 'NETCONF: Operation to change configuration?', a: 'edit-config' },
  { id: '3-14', domain: Domain.NXOS, q: 'NETCONF: Operation to retrieve running config?', a: 'get-config' },
  { id: '3-15', domain: Domain.NXOS, q: 'NETCONF: Default edit operation (merge/replace/none)?', a: 'merge' },
  { id: '3-16', domain: Domain.NXOS, q: 'gNMI: Supported encoding formats?', a: 'JSON, Bytes (Protobuf)' },
  { id: '3-17', domain: Domain.NXOS, q: 'gNMI: RPC to stream data?', a: 'Subscribe' },
  { id: '3-18', domain: Domain.NXOS, q: 'Telemetry: "Dial-out" means?', a: 'Device initiates connection to collector' },
  { id: '3-19', domain: Domain.NXOS, q: 'Telemetry: "Dial-in" means?', a: 'Collector initiates connection to device' },
  { id: '3-20', domain: Domain.NXOS, q: 'NX-OS Telemetry: Interval unit?', a: 'Milliseconds' },
  { id: '3-21', domain: Domain.NXOS, q: 'YANG: Google-defined vendor-neutral models?', a: 'OpenConfig' },
  { id: '3-22', domain: Domain.NXOS, q: 'YANG: Cisco specific models?', a: 'Native' },
  { id: '3-23', domain: Domain.NXOS, q: 'NX-API: Default HTTP port?', a: '80' },
  { id: '3-24', domain: Domain.NXOS, q: 'NX-API: Default HTTPS port?', a: '443' },
  { id: '3-25', domain: Domain.NXOS, q: 'NX-API: Sandbox URL?', a: '/ins' },
  { id: '3-26', domain: Domain.NXOS, q: 'NETCONF: Filter type to select specific nodes?', a: 'subtree' },
  { id: '3-27', domain: Domain.NXOS, q: 'EEM: Event detector for syslog?', a: 'event syslog' },
  { id: '3-28', domain: Domain.NXOS, q: 'EEM: Event detector for CLI command?', a: 'event cli match' },
  { id: '3-29', domain: Domain.NXOS, q: 'Guest Shell: Packet manager?', a: 'yum' },
  { id: '3-30', domain: Domain.NXOS, q: 'NX-OS Python: How to separate multiple commands in one string?', a: ' ; (semicolon)' },
  { id: '3-31', domain: Domain.NXOS, q: 'Model Driven Telemetry: Encoding using Key/Value pairs?', a: 'GPB-KV (Google Protobuf Key Value)' },
  { id: '3-32', domain: Domain.NXOS, q: 'Model Driven Telemetry: Compact encoding?', a: 'GPB (Google Protobuf)' },
  { id: '3-33', domain: Domain.NXOS, q: 'NETCONF: Python library often used?', a: 'ncclient' },
  { id: '3-34', domain: Domain.NXOS, q: 'NX-API REST: Payload format?', a: 'JSON or XML' },
  { id: '3-35', domain: Domain.NXOS, q: 'NX-OS: Feature to enable API?', a: 'feature nxapi' },
  { id: '3-36', domain: Domain.NXOS, q: 'NX-OS: Feature to enable NETCONF?', a: 'feature netconf' },
  { id: '3-37', domain: Domain.NXOS, q: 'NX-OS: Feature to enable Bash?', a: 'feature bash-shell' },
  { id: '3-38', domain: Domain.NXOS, q: 'gNMI: Transport protocol?', a: 'HTTP/2 (gRPC)' },
  { id: '3-39', domain: Domain.NXOS, q: 'POAP: DHCP option for script URI?', a: 'Option 66/67' },
  { id: '3-40', domain: Domain.NXOS, q: 'YANG: Leaf node constraint?', a: 'must' },

  // --- 4.0 UCS/Intersight ---
  { id: '4-1', domain: Domain.UCS, q: 'UCS Python SDK: Function to add an MO?', a: 'add_mo' },
  { id: '4-2', domain: Domain.UCS, q: 'UCS Python SDK: Argument to update if exists?', a: 'modify_present=True' },
  { id: '4-3', domain: Domain.UCS, q: 'UCS Python SDK: Is there a set_mo function?', a: 'No (use add_mo with modify_present)' },
  { id: '4-4', domain: Domain.UCS, q: 'LsServer: Type for a Service Profile Template?', a: 'initial-template / updating-template' },
  { id: '4-5', domain: Domain.UCS, q: 'LsServer: Type for a Service Profile Instance?', a: 'instance' },
  { id: '4-6', domain: Domain.UCS, q: 'PowerTool: Pattern to modify objects?', a: 'Get-UcsX | Set-UcsX' },
  { id: '4-7', domain: Domain.UCS, q: 'PowerTool: Flag to confirm XML output?', a: '-Xml' },
  { id: '4-8', domain: Domain.UCS, q: 'Intersight Auth: Hashing algorithm for body?', a: 'SHA256' },
  { id: '4-9', domain: Domain.UCS, q: 'Intersight Auth: Signature algorithm?', a: 'RSA' },
  { id: '4-10', domain: Domain.UCS, q: 'Intersight API: Mandatory relationship for most resources?', a: 'Organization' },
  { id: '4-11', domain: Domain.UCS, q: 'Intersight API: Organization reference requires?', a: 'moid and object_type' },
  { id: '4-12', domain: Domain.UCS, q: 'Terraform Intersight: Authentication requires?', a: 'apikey and secretkey (file)' },
  { id: '4-13', domain: Domain.UCS, q: 'UCS Python SDK: Module to import?', a: 'ucsmsdk' },
  { id: '4-14', domain: Domain.UCS, q: 'UCS Manager: XML API endpoint?', a: '/nuova' },
  { id: '4-15', domain: Domain.UCS, q: 'Intersight: Query parameter to filter?', a: '$filter' },
  { id: '4-16', domain: Domain.UCS, q: 'Intersight: Query parameter to select specific fields?', a: '$select' },
  { id: '4-17', domain: Domain.UCS, q: 'UCS Class: Compute Blade?', a: 'computeBlade' },
  { id: '4-18', domain: Domain.UCS, q: 'UCS Class: Rack Unit?', a: 'computeRackUnit' },
  { id: '4-19', domain: Domain.UCS, q: 'Intersight: Header containing the signature?', a: 'Authorization' },
  { id: '4-20', domain: Domain.UCS, q: 'Intersight: Header containing the date?', a: 'Date (or X-Date)' },
  { id: '4-21', domain: Domain.UCS, q: 'UCS Python SDK: Login handle class?', a: 'UcsHandle' },
  { id: '4-22', domain: Domain.UCS, q: 'PowerTool: Cmdlet to connect?', a: 'Connect-Ucs' },
  { id: '4-23', domain: Domain.UCS, q: 'PowerTool: Cmdlet to disconnect?', a: 'Disconnect-Ucs' },
  { id: '4-24', domain: Domain.UCS, q: 'Intersight: Object Type for physical server?', a: 'compute.PhysicalSummary' },
  { id: '4-25', domain: Domain.UCS, q: 'Intersight: Object Type for organization?', a: 'organization.Organization' },
  { id: '4-26', domain: Domain.UCS, q: 'Terraform Intersight: Provider name?', a: 'CiscoDevNet/intersight' },
  { id: '4-27', domain: Domain.UCS, q: 'UCS Python: Query class objects?', a: 'handle.query_classid("classId")' },
  { id: '4-28', domain: Domain.UCS, q: 'UCS Python: Commit transaction?', a: 'handle.commit()' },
  { id: '4-29', domain: Domain.UCS, q: 'UCS Python: Logout?', a: 'handle.logout()' },
  { id: '4-30', domain: Domain.UCS, q: 'Intersight API: Base URL?', a: 'https://intersight.com/api/v1' },
];